/**
 * Studios API
 * Handles studio/workspace operations
 */

import { apiDownload, apiFetch } from "./api-client";
import { getAccessToken } from "./auth";
import type { components } from "./types";

export type StudioMemberResponse = components["schemas"]["StudioMemberResponse"];
export type GroupInfoItem = components["schemas"]["GroupInfoItem"];

// Subscription info from /studio API response
export type StudioListSubscription = {
    studioCreated: number;
    studioLimit: number;
};

// Full response from /studio API
export type StudioListResponse = {
    studios: StudioUI[];
    subscription: StudioListSubscription;
};

export type Studio = {
    studioId: string;
    studioName: string;
    description: string;
    ownerId: string;
    createdAt: string;
    updatedAt: string;
    groupCount: number;
    completionProgress?: number; // Tiến độ hoàn thiện trung bình (%)
    studioRole?: 0 | 1; // 0 = Owner, 1 = Member
    startDate?: string | null; // NEW
    endDate?: string | null; // NEW
};

// Map API response to UI format
export type StudioUI = {
    id: string;
    name: string;
    description: string;
    type: "personal" | "group";
    memberCount: number;
    groupCount: number;
    completionProgress: number; // Tiến độ hoàn thiện trung bình (%)
    createdAt: string;
    updatedAt: string;
    studioRole?: 0 | 1; // 0 = Owner, 1 = Member
    startDate?: string | null; // NEW
    endDate?: string | null; // NEW
};

export type CreateStudioRequest = {
    name: string;
    description: string;
    type: "personal" | "group";
    startDate?: string | null;
    endDate?: string | null;
};

export type UpdateStudioRequest = {
    name?: string;
    description?: string;
    type?: "personal" | "group";
    startDate?: string | null; // NEW
    endDate?: string | null; // NEW
};

// Helper: convert ISO datetime string to YYYY-MM-DD for <input type="date">
function toDateInputValue(dateStr: string | null | undefined): string {
    if (!dateStr) return "";
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return "";
    return d.toISOString().slice(0, 10); // YYYY-MM-DD
}

// Helper function to map API Studio to UI Studio
function mapStudioToUI(studio: Studio): StudioUI {
    return {
        id: studio.studioId,
        name: studio.studioName,
        description: studio.description,
        type: "group", // API không có type, mặc định là group
        memberCount: 0, // Sẽ được tính từ tổng members trong các groups
        groupCount: studio.groupCount,
        completionProgress: studio.completionProgress || 0, // Tiến độ hoàn thiện từ API
        createdAt: studio.createdAt,
        updatedAt: studio.updatedAt,
        studioRole: studio.studioRole, // 0 = Owner, 1 = Member
        startDate: toDateInputValue(studio.startDate), // NEW — YYYY-MM-DD for <input type="date">
        endDate: toDateInputValue(studio.endDate) // NEW — YYYY-MM-DD for <input type="date">
    };
}

/**
 * Get list of studios
 */
export async function getStudios(locale = "vi") {
    const result = await apiFetch<{ studios: Studio[]; subscription?: StudioListSubscription }>("/studio", {
        method: "GET",
        locale
    });

    // Map API response to UI format
    if (result.status === "success" && result.data) {
        const mappedStudios = result.data.studios.map(mapStudioToUI);
        return {
            ...result,
            data: {
                studios: mappedStudios,
                subscription: result.data.subscription || {
                    studioCreated: mappedStudios.length,
                    studioLimit: 3
                }
            } as StudioListResponse
        };
    }

    return result as any;
}

/**
 * Get studio by ID
 */
export async function getStudioById(id: string, locale = "vi") {
    const result = await apiFetch<Studio>(`/studio/${id}`, {
        method: "GET",
        locale
    });

    // Map API response to UI format
    if (result.status === "success" && result.data) {
        return {
            ...result,
            data: mapStudioToUI(result.data)
        };
    }

    return result as any;
}

/**
 * Create new studio
 */
export async function createStudio(data: CreateStudioRequest, locale = "vi") {
    // API only needs studioName and description
    // ownerId, createdAt, updatedAt are generated by backend
    const result = await apiFetch<Studio>("/studio", {
        method: "POST",
        body: JSON.stringify({
            studioName: data.name,
            description: data.description,
            startDate: data.startDate ?? null,
            endDate: data.endDate ?? null
        }),
        locale
    });

    // Map API response to UI format
    if (result.status === "success" && result.data) {
        return {
            ...result,
            data: mapStudioToUI(result.data)
        };
    }

    return result as any;
}

/**
 * Update studio
 */
export async function updateStudio(id: string, data: UpdateStudioRequest, locale = "vi") {
    // API PUT needs id in body along with studioName and description
    const result = await apiFetch<{ studioName: string; description: string; updatedAt: string }>("/studio", {
        method: "PUT",
        body: JSON.stringify({
            id: id,
            studioName: data.name,
            description: data.description,
            startDate: data.startDate ?? null,
            endDate: data.endDate ?? null
        }),
        locale
    });

    return result as any;
}

/**
 * Delete studio
 */
export async function deleteStudio(id: string, locale = "vi") {
    return apiFetch<null>(`/studio/${id}`, {
        method: "DELETE",
        locale
    });
}

/**
 * Get studio members
 */
export async function getStudioMembers(studioId: string, locale = "vi") {
    return apiFetch<StudioMemberResponse[]>(`/studio/${studioId}/members`, {
        method: "GET",
        locale
    });
}

// Batch assign types
export type BatchAssignResponse = components["schemas"]["BatchAssignResponse"];
export type BatchErrorRow = components["schemas"]["BatchErrorRow"];

// Build API URL helper
function buildStudioApiUrl(path: string) {
    const baseUrl = (process.env.NEXT_PUBLIC_API_BASE_URL || "").replace(/\/$/, "");
    return `${baseUrl}${path}`;
}

/**
 * Download CSV template for batch assign
 */
export async function downloadBatchAssignTemplate(studioId: string): Promise<Blob> {
    return apiDownload(buildStudioApiUrl(`/studio/${studioId}/members/batch-assign/template`));
}

/**
 * Upload batch-assign CSV file
 */
export async function uploadBatchAssignCsv(
    studioId: string,
    file: File
): Promise<components["schemas"]["BatchAssignResponseApiResponse"]> {
    const fullUrl = buildStudioApiUrl(`/studio/${studioId}/members/batch-assign`);

    const formData = new FormData();
    formData.append("file", file);

    const token = getAccessToken();
    const response = await fetch(fullUrl, {
        method: "POST",
        headers: {
            Authorization: `Bearer ${token}`
            // NOTE: no Content-Type header — browser auto-sets multipart boundary for FormData
        },
        body: formData
    });

    return response.json();
}

// Random assign types
export type RandomAssignRequest = components["schemas"]["RandomAssignRequest"];
export type RandomAssignResponseApiResponse = components["schemas"]["RandomAssignResponseApiResponse"];

/**
 * Randomly assign studio members to groups
 */
export async function randomAssignMembers(
    studioId: string,
    body: RandomAssignRequest,
    locale = "vi"
): Promise<RandomAssignResponseApiResponse> {
    const fullUrl = buildStudioApiUrl(`/studio/${studioId}/groups/random-assign`);

    const token = getAccessToken();
    const response = await fetch(fullUrl, {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "Accept-Language": locale,
            Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(body)
    });

    return response.json();
}
