/**
 * Studios API
 * Handles studio/workspace operations
 */

import { apiFetch } from "./api-client";

export type Studio = {
    studioId: string;
    studioName: string;
    description: string;
    ownerId: string;
    createdAt: string;
    updatedAt: string;
    groupCount: number;
};

// Map API response to UI format
export type StudioUI = {
    id: string;
    name: string;
    description: string;
    type: "personal" | "group";
    memberCount: number;
    videoCount: number;
    createdAt: string;
    updatedAt: string;
};

export type CreateStudioRequest = {
    name: string;
    description: string;
    type: "personal" | "group";
};

export type UpdateStudioRequest = {
    name?: string;
    description?: string;
    type?: "personal" | "group";
};

// Helper function to map API Studio to UI Studio
function mapStudioToUI(studio: Studio): StudioUI {
    return {
        id: studio.studioId,
        name: studio.studioName,
        description: studio.description,
        type: "group", // API không có type, mặc định là group
        memberCount: studio.groupCount,
        videoCount: 0, // API không có videoCount
        createdAt: studio.createdAt,
        updatedAt: studio.updatedAt
    };
}

/**
 * Get list of studios
 */
export async function getStudios(locale = "vi") {
    const baseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || "";
    const result = await apiFetch<Studio[]>(`${baseUrl}/studio`, {
        method: "GET",
        locale
    });

    // Map API response to UI format
    if (result.status === "success" && result.data) {
        const mappedData = result.data.map(mapStudioToUI);
        return {
            ...result,
            data: mappedData
        };
    }

    return result as any;
}

/**
 * Get studio by ID
 */
export async function getStudioById(id: string, locale = "vi") {
    const baseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || "";
    const result = await apiFetch<Studio>(`${baseUrl}/studio/${id}`, {
        method: "GET",
        locale
    });

    // Map API response to UI format
    if (result.status === "success" && result.data) {
        return {
            ...result,
            data: mapStudioToUI(result.data)
        };
    }

    return result as any;
}

/**
 * Create new studio
 */
export async function createStudio(data: CreateStudioRequest, locale = "vi") {
    const baseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || "";

    // API only needs studioName and description
    // ownerId, createdAt, updatedAt are generated by backend
    const result = await apiFetch<Studio>(`${baseUrl}/studio`, {
        method: "POST",
        body: JSON.stringify({
            studioName: data.name,
            description: data.description
        }),
        locale
    });

    // Map API response to UI format
    if (result.status === "success" && result.data) {
        return {
            ...result,
            data: mapStudioToUI(result.data)
        };
    }

    return result as any;
}

/**
 * Update studio
 */
export async function updateStudio(id: string, data: UpdateStudioRequest, locale = "vi") {
    const baseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || "";

    // API PUT needs id in body along with studioName and description
    const result = await apiFetch<{ studioName: string; description: string; updatedAt: string }>(`${baseUrl}/studio`, {
        method: "PUT",
        body: JSON.stringify({
            id: id,
            studioName: data.name,
            description: data.description
        }),
        locale
    });

    return result as any;
}

/**
 * Delete studio
 */
export async function deleteStudio(id: string, locale = "vi") {
    const baseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || "";
    return apiFetch<null>(`${baseUrl}/studio/${id}`, {
        method: "DELETE",
        locale
    });
}
