/**
 * Studios API
 * Handles studio/workspace operations
 */

import { apiFetch } from "./api-client";
import type { components } from "./types";

export type StudioMemberResponse = components["schemas"]["StudioMemberResponse"];
export type GroupInfoItem = components["schemas"]["GroupInfoItem"];

export type Studio = {
    studioId: string;
    studioName: string;
    description: string;
    ownerId: string;
    createdAt: string;
    updatedAt: string;
    groupCount: number;
    completionProgress?: number; // Tiến độ hoàn thiện trung bình (%)
};

// Map API response to UI format
export type StudioUI = {
    id: string;
    name: string;
    description: string;
    type: "personal" | "group";
    memberCount: number;
    groupCount: number;
    completionProgress: number; // Tiến độ hoàn thiện trung bình (%)
    createdAt: string;
    updatedAt: string;
};

export type CreateStudioRequest = {
    name: string;
    description: string;
    type: "personal" | "group";
};

export type UpdateStudioRequest = {
    name?: string;
    description?: string;
    type?: "personal" | "group";
};

// Helper function to map API Studio to UI Studio
function mapStudioToUI(studio: Studio): StudioUI {
    return {
        id: studio.studioId,
        name: studio.studioName,
        description: studio.description,
        type: "group", // API không có type, mặc định là group
        memberCount: 0, // Sẽ được tính từ tổng members trong các groups
        groupCount: studio.groupCount,
        completionProgress: studio.completionProgress || 0, // Tiến độ hoàn thiện từ API
        createdAt: studio.createdAt,
        updatedAt: studio.updatedAt
    };
}

/**
 * Get list of studios
 */
export async function getStudios(locale = "vi") {
    const result = await apiFetch<Studio[]>("/studio", {
        method: "GET",
        locale
    });

    // Map API response to UI format
    if (result.status === "success" && result.data) {
        const mappedData = result.data.map(mapStudioToUI);
        return {
            ...result,
            data: mappedData
        };
    }

    return result as any;
}

/**
 * Get studio by ID
 */
export async function getStudioById(id: string, locale = "vi") {
    const result = await apiFetch<Studio>(`/studio/${id}`, {
        method: "GET",
        locale
    });

    // Map API response to UI format
    if (result.status === "success" && result.data) {
        return {
            ...result,
            data: mapStudioToUI(result.data)
        };
    }

    return result as any;
}

/**
 * Create new studio
 */
export async function createStudio(data: CreateStudioRequest, locale = "vi") {
    // API only needs studioName and description
    // ownerId, createdAt, updatedAt are generated by backend
    const result = await apiFetch<Studio>("/studio", {
        method: "POST",
        body: JSON.stringify({
            studioName: data.name,
            description: data.description
        }),
        locale
    });

    // Map API response to UI format
    if (result.status === "success" && result.data) {
        return {
            ...result,
            data: mapStudioToUI(result.data)
        };
    }

    return result as any;
}

/**
 * Update studio
 */
export async function updateStudio(id: string, data: UpdateStudioRequest, locale = "vi") {
    // API PUT needs id in body along with studioName and description
    const result = await apiFetch<{ studioName: string; description: string; updatedAt: string }>("/studio", {
        method: "PUT",
        body: JSON.stringify({
            id: id,
            studioName: data.name,
            description: data.description
        }),
        locale
    });

    return result as any;
}

/**
 * Delete studio
 */
export async function deleteStudio(id: string, locale = "vi") {
    return apiFetch<null>(`/studio/${id}`, {
        method: "DELETE",
        locale
    });
}

/**
 * Get studio members
 */
export async function getStudioMembers(studioId: string, locale = "vi") {
    return apiFetch<StudioMemberResponse[]>(`/studio/${studioId}/members`, {
        method: "GET",
        locale
    });
}
