/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateResponseListApiResponse"];
                        "text/json": components["schemas"]["TemplateResponseListApiResponse"];
                        "text/plain": components["schemas"]["TemplateResponseListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["CreateTemplateRequest"];
                    "application/json": components["schemas"]["CreateTemplateRequest"];
                    "text/json": components["schemas"]["CreateTemplateRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateResponseApiResponse"];
                        "text/json": components["schemas"]["TemplateResponseApiResponse"];
                        "text/plain": components["schemas"]["TemplateResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateResponseApiResponse"];
                        "text/json": components["schemas"]["TemplateResponseApiResponse"];
                        "text/plain": components["schemas"]["TemplateResponseApiResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["UpdateTemplateRequest"];
                    "application/json": components["schemas"]["UpdateTemplateRequest"];
                    "text/json": components["schemas"]["UpdateTemplateRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateResponseApiResponse"];
                        "text/json": components["schemas"]["TemplateResponseApiResponse"];
                        "text/plain": components["schemas"]["TemplateResponseApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnnouncementResponseListApiResponse"];
                        "text/json": components["schemas"]["AnnouncementResponseListApiResponse"];
                        "text/plain": components["schemas"]["AnnouncementResponseListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/announcements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["ForgotPasswordRequest"];
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                    "text/json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["GoogleLoginRequest"];
                    "application/json": components["schemas"]["GoogleLoginRequest"];
                    "text/json": components["schemas"]["GoogleLoginRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["LoginRequests"];
                    "application/json": components["schemas"]["LoginRequests"];
                    "text/json": components["schemas"]["LoginRequests"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponseApiResponse"];
                        "text/json": components["schemas"]["LoginResponseApiResponse"];
                        "text/plain": components["schemas"]["LoginResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponseApiResponse"];
                        "text/json": components["schemas"]["LoginResponseApiResponse"];
                        "text/plain": components["schemas"]["LoginResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["RegisterRequests"];
                    "application/json": components["schemas"]["RegisterRequests"];
                    "text/json": components["schemas"]["RegisterRequests"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-email-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["ResendVerifyEmailRequest"];
                    "application/json": components["schemas"]["ResendVerifyEmailRequest"];
                    "text/json": components["schemas"]["ResendVerifyEmailRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["ResetPasswordRequest"];
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                    "text/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-reset-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["ChangePasswordRequest"];
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                    "text/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favourite/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["AddFavouriteRequest"];
                    "application/json": components["schemas"]["AddFavouriteRequest"];
                    "text/json": components["schemas"]["AddFavouriteRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FavouriteResponseApiResponse"];
                        "text/json": components["schemas"]["FavouriteResponseApiResponse"];
                        "text/plain": components["schemas"]["FavouriteResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favourite/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["RemoveFavouriteRequest"];
                    "application/json": components["schemas"]["RemoveFavouriteRequest"];
                    "text/json": components["schemas"]["RemoveFavouriteRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GroupListResponseApiResponse"];
                        "text/json": components["schemas"]["GroupListResponseApiResponse"];
                        "text/plain": components["schemas"]["GroupListResponseApiResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["UpdateGroupRequest"];
                    "application/json": components["schemas"]["UpdateGroupRequest"];
                    "text/json": components["schemas"]["UpdateGroupRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateGroupResponseApiResponse"];
                        "text/json": components["schemas"]["UpdateGroupResponseApiResponse"];
                        "text/plain": components["schemas"]["UpdateGroupResponseApiResponse"];
                    };
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["CreateGroupRequest"];
                    "application/json": components["schemas"]["CreateGroupRequest"];
                    "text/json": components["schemas"]["CreateGroupRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateGroupResponseApiResponse"];
                        "text/json": components["schemas"]["CreateGroupResponseApiResponse"];
                        "text/plain": components["schemas"]["CreateGroupResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/member/assign-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["AssignRoleRequest"];
                    "application/json": components["schemas"]["AssignRoleRequest"];
                    "text/json": components["schemas"]["AssignRoleRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssignRoleResponseApiResponse"];
                        "text/json": components["schemas"]["AssignRoleResponseApiResponse"];
                        "text/plain": components["schemas"]["AssignRoleResponseApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/member/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["RemoveMemberRequest"];
                    "application/json": components["schemas"]["RemoveMemberRequest"];
                    "text/json": components["schemas"]["RemoveMemberRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RemoveMemberResponseApiResponse"];
                        "text/json": components["schemas"]["RemoveMemberResponseApiResponse"];
                        "text/plain": components["schemas"]["RemoveMemberResponseApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invite/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["AcceptInviteLinkRequest"];
                    "application/json": components["schemas"]["AcceptInviteLinkRequest"];
                    "text/json": components["schemas"]["AcceptInviteLinkRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AcceptInviteLinkResponseApiResponse"];
                        "text/json": components["schemas"]["AcceptInviteLinkResponseApiResponse"];
                        "text/plain": components["schemas"]["AcceptInviteLinkResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invite/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["CreateInviteLinkRequest"];
                    "application/json": components["schemas"]["CreateInviteLinkRequest"];
                    "text/json": components["schemas"]["CreateInviteLinkRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateInviteLinkResponseApiResponse"];
                        "text/json": components["schemas"]["CreateInviteLinkResponseApiResponse"];
                        "text/plain": components["schemas"]["CreateInviteLinkResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invite/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["SendInviteEmailRequest"];
                    "application/json": components["schemas"]["SendInviteEmailRequest"];
                    "text/json": components["schemas"]["SendInviteEmailRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["ReportRequest"];
                    "application/json": components["schemas"]["ReportRequest"];
                    "text/json": components["schemas"]["ReportRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudioResponseListApiResponse"];
                        "text/json": components["schemas"]["StudioResponseListApiResponse"];
                        "text/plain": components["schemas"]["StudioResponseListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/*+json": components["schemas"]["CreateStudioRequest"];
                    "application/json": components["schemas"]["CreateStudioRequest"];
                    "text/json": components["schemas"]["CreateStudioRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudioResponseApiResponse"];
                        "text/json": components["schemas"]["StudioResponseApiResponse"];
                        "text/plain": components["schemas"]["StudioResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateResponseListApiResponse"];
                        "text/json": components["schemas"]["TemplateResponseListApiResponse"];
                        "text/plain": components["schemas"]["TemplateResponseListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateResponseApiResponse"];
                        "text/json": components["schemas"]["TemplateResponseApiResponse"];
                        "text/plain": components["schemas"]["TemplateResponseApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/personal-status/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/personal-task/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/personal-task/{userId}/{statusId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    statusId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfileResponseApiResponse"];
                        "text/json": components["schemas"]["UserProfileResponseApiResponse"];
                        "text/plain": components["schemas"]["UserProfileResponseApiResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        Avatar?: string;
                        Bio?: string;
                        EmailNotificationEnabled?: boolean;
                        FirstName?: string;
                        Language?: string;
                        LastName?: string;
                        /** Format: tel */
                        PhoneNumber?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInviteLinkRequest: {
            token: string;
        };
        AcceptInviteLinkResponse: {
            /** Format: uuid */
            groupId?: string;
            groupName?: string | null;
            /** Format: date-time */
            joinedAt?: string;
            role?: string | null;
        };
        AcceptInviteLinkResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["AcceptInviteLinkResponse"];
            message?: string | null;
            status?: string | null;
        };
        AddFavouriteRequest: {
            /** Format: uuid */
            groupId: string;
        };
        AnnouncementResponse: {
            /** Format: uuid */
            announcementId?: string;
            content?: string | null;
            /** Format: date-time */
            createdAt?: string;
            isActive?: boolean;
            /** Format: date-time */
            publishedAt?: string | null;
            title?: string | null;
            type?: string | null;
        };
        AnnouncementResponseListApiResponse: {
            code?: string | null;
            data?: components["schemas"]["AnnouncementResponse"][] | null;
            message?: string | null;
            status?: string | null;
        };
        AssignRoleRequest: {
            /** Format: uuid */
            groupId: string;
            role: string;
            /** Format: uuid */
            userId: string;
        };
        AssignRoleResponse: {
            /** Format: uuid */
            groupId?: string;
            groupName?: string | null;
            newRole?: string | null;
            oldRole?: string | null;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            userId?: string;
            userName?: string | null;
        };
        AssignRoleResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["AssignRoleResponse"];
            message?: string | null;
            status?: string | null;
        };
        ChangePasswordRequest: {
            confirmPassword: string;
            currentPassword: string;
            newPassword: string;
        };
        CreateGroupRequest: {
            description?: string | null;
            groupName: string;
            /** Format: uuid */
            studioId?: string | null;
            /** Format: uuid */
            templateId?: string | null;
        };
        CreateGroupResponse: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            createdBy?: string;
            description?: string | null;
            /** Format: uuid */
            groupId?: string;
            groupName?: string | null;
            groupType?: string | null;
            /** Format: uuid */
            studioId?: string | null;
        };
        CreateGroupResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["CreateGroupResponse"];
            message?: string | null;
            status?: string | null;
        };
        CreateInviteLinkRequest: {
            /** Format: uuid */
            groupId: string;
            role: string;
        };
        CreateInviteLinkResponse: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            inviteUrl?: string | null;
            role?: string | null;
            token?: string | null;
        };
        CreateInviteLinkResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["CreateInviteLinkResponse"];
            message?: string | null;
            status?: string | null;
        };
        CreateStudioRequest: {
            /** Format: date-time */
            createdAt?: string;
            description?: string | null;
            /** Format: uuid */
            ownerId?: string;
            studioName?: string | null;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateTemplateRequest: {
            description?: string | null;
            groupName: string;
            groupTaskStatuses: components["schemas"]["GroupTaskStatusRequest"][];
        };
        FavouriteResponse: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            favouriteId?: string;
            /** Format: uuid */
            groupId?: string;
            groupName?: string | null;
        };
        FavouriteResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["FavouriteResponse"];
            message?: string | null;
            status?: string | null;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        GoogleLoginRequest: {
            idToken: string;
        };
        GroupCardDto: {
            createdBy?: components["schemas"]["UserDto"];
            description?: string | null;
            /** Format: uuid */
            id?: string;
            isFavorite?: boolean;
            /** Format: date-time */
            lastActivityAt?: string;
            /** Format: int32 */
            memberCount?: number;
            membersPreview?: components["schemas"]["MemberPreviewDto"][] | null;
            name?: string | null;
            role?: string | null;
            studio?: components["schemas"]["StudioDto"];
            /** Format: int32 */
            taskCount?: number;
        };
        GroupListResponse: {
            sections?: components["schemas"]["GroupSections"];
            subscription?: components["schemas"]["SubscriptionInfo"];
            summary?: components["schemas"]["GroupSummary"];
        };
        GroupListResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["GroupListResponse"];
            message?: string | null;
            status?: string | null;
        };
        GroupSections: {
            favorites?: components["schemas"]["GroupCardDto"][] | null;
            independentGroups?: components["schemas"]["GroupCardDto"][] | null;
            studioGroups?: components["schemas"]["GroupCardDto"][] | null;
        };
        GroupSummary: {
            /** Format: int32 */
            favoriteCount?: number;
            /** Format: int32 */
            independentGroupCount?: number;
            /** Format: int32 */
            studioGroupCount?: number;
            /** Format: int32 */
            totalGroups?: number;
        };
        GroupTaskStatusRequest: {
            /** Format: int32 */
            position: number;
            statusName: string;
        };
        LoginRequests: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            /** Format: int64 */
            accessExpireIn?: number;
            accessToken?: string | null;
            email?: string | null;
            firstName?: string | null;
            /** Format: uuid */
            id?: string;
            lastName?: string | null;
            /** Format: int64 */
            refreshExpireIn?: number;
            refreshToken?: string | null;
        };
        LoginResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["LoginResponse"];
            message?: string | null;
            status?: string | null;
        };
        MemberPreviewDto: {
            avatarUrl?: string | null;
            firstName?: string | null;
            /** Format: uuid */
            id?: string;
            lastName?: string | null;
        };
        ObjectApiResponse: {
            code?: string | null;
            data?: unknown;
            message?: string | null;
            status?: string | null;
        };
        RegisterRequests: {
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
            password: string;
        };
        RemoveFavouriteRequest: {
            /** Format: uuid */
            groupId: string;
        };
        RemoveMemberRequest: {
            /** Format: uuid */
            groupId: string;
            /** Format: uuid */
            userId: string;
        };
        RemoveMemberResponse: {
            /** Format: uuid */
            groupId?: string;
            groupName?: string | null;
            /** Format: date-time */
            removedAt?: string;
            /** Format: uuid */
            removedUserId?: string;
            removedUserName?: string | null;
        };
        RemoveMemberResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["RemoveMemberResponse"];
            message?: string | null;
            status?: string | null;
        };
        ReportRequest: {
            content: string;
            /** Format: email */
            email: string;
            title: string;
            type: string;
        };
        ResendVerifyEmailRequest: {
            email?: string | null;
        };
        ResetPasswordRequest: {
            newPassword: string;
            token: string;
        };
        SendInviteEmailRequest: {
            /** Format: email */
            email: string;
            /** Format: uuid */
            groupId: string;
            role: string;
        };
        StudioDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
        };
        StudioResponse: {
            /** Format: date-time */
            createdAt?: string;
            description?: string | null;
            /** Format: int32 */
            groupCount?: number;
            /** Format: uuid */
            ownerId?: string;
            /** Format: uuid */
            studioId?: string;
            studioName?: string | null;
            /** Format: date-time */
            updatedAt?: string;
        };
        StudioResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["StudioResponse"];
            message?: string | null;
            status?: string | null;
        };
        StudioResponseListApiResponse: {
            code?: string | null;
            data?: components["schemas"]["StudioResponse"][] | null;
            message?: string | null;
            status?: string | null;
        };
        SubscriptionInfo: {
            /** Format: int32 */
            groupCreated?: number;
            /** Format: int32 */
            groupLimit?: number;
            /** Format: int32 */
            memberLimit?: number;
        };
        TemplateResponse: {
            /** Format: date-time */
            createdAt?: string;
            groupDescription?: string | null;
            /** Format: uuid */
            groupId?: string;
            groupName?: string | null;
            isSystemTemplate?: boolean;
            /** Format: uuid */
            templateId?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            userId?: string;
        };
        TemplateResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["TemplateResponse"];
            message?: string | null;
            status?: string | null;
        };
        TemplateResponseListApiResponse: {
            code?: string | null;
            data?: components["schemas"]["TemplateResponse"][] | null;
            message?: string | null;
            status?: string | null;
        };
        UpdateGroupRequest: {
            description?: string | null;
            /** Format: uuid */
            groupId: string;
            groupName: string;
            isTemplate?: boolean;
        };
        UpdateGroupResponse: {
            description?: string | null;
            /** Format: uuid */
            groupId?: string;
            groupName?: string | null;
            groupType?: string | null;
            isTemplate?: boolean;
            /** Format: uuid */
            studioId?: string | null;
            /** Format: uuid */
            templateId?: string | null;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdateGroupResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["UpdateGroupResponse"];
            message?: string | null;
            status?: string | null;
        };
        UpdateTemplateRequest: {
            /** Format: uuid */
            groupId: string;
            isSystemTemplate?: boolean;
        };
        UserDto: {
            avatarUrl?: string | null;
            firstName?: string | null;
            /** Format: uuid */
            id?: string;
            lastName?: string | null;
        };
        UserProfileResponse: {
            avatarUrl?: string | null;
            bio?: string | null;
            /** Format: date-time */
            createdAt?: string;
            email?: string | null;
            emailNotificationEnabled?: boolean;
            firstName?: string | null;
            googleId?: string | null;
            isAdmin?: boolean;
            language?: string | null;
            lastName?: string | null;
            phoneNumber?: string | null;
            status?: string | null;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            userId?: string;
        };
        UserProfileResponseApiResponse: {
            code?: string | null;
            data?: components["schemas"]["UserProfileResponse"];
            message?: string | null;
            status?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
